#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="/home/tang/matd3"
cd "$ROOT_DIR"

LABEL="${LABEL_OVERRIDE:-matd3_cross_agent_ref_reward_to_success_head_tail_selector}"
RUN_TAG="${RUN_TAG:-level3_r2s_selector_oldstart_seed101_hold5_ep1200_matchedval_official10x30_$(date +%Y%m%d_%H%M%S)}"
BASE_SPEC="${BASE_SPEC:-$ROOT_DIR/ablation_experiments/multi_seed_groupB_20260615_223008/seed_batches/batch_groupB_seed101_20260615_223008/results/post_eval_shared_spec.json}"
CHECKPOINT_CANDIDATES="${CHECKPOINT_CANDIDATES:-best_by_team_sr,best,checkpoint,final,latest_ep,ep100,ep200,ep300,ep400,ep500,ep600,ep700,ep800,ep900,ep1000,ep1100,ep1200}"
CROSS_REF_START_EPISODE="${CROSS_AGENT_REFERENCE_START_EPISODE:-50}"
CROSS_REF_ACTOR_START_EPISODE="${CROSS_AGENT_REFERENCE_ACTOR_START_EPISODE:-$CROSS_REF_START_EPISODE}"
CROSS_REF_ACTOR_RAMP_EPISODES="${CROSS_AGENT_REFERENCE_ACTOR_RAMP_EPISODES:-0}"
CROSS_REF_ACTOR_REQUIRE_SUCCESS="${CROSS_AGENT_REFERENCE_ACTOR_REQUIRE_SUCCESS:-0}"

TRAIN_LABELS_OVERRIDE="${TRAIN_LABELS_OVERRIDE:-$LABEL}" \
EVAL_LABELS_OVERRIDE="${EVAL_LABELS_OVERRIDE:-$LABEL}" \
RUN_TAG="$RUN_TAG" \
BASE_SPEC="$BASE_SPEC" \
TRAIN_SEEDS="${TRAIN_SEEDS:-101}" \
EVAL_SEEDS="${EVAL_SEEDS:-30088 30188 30288 30388 30488 30588 30688 30788 30888 30988}" \
EPISODES="${EPISODES:-1200}" \
TRAIN_EPISODES="${TRAIN_EPISODES:-1200}" \
EVAL_EPISODES="${EVAL_EPISODES:-30}" \
POST_EVAL_EPISODES="${POST_EVAL_EPISODES:-30}" \
MAX_PARALLEL="${MAX_PARALLEL:-1}" \
TRAIN_MAX_PARALLEL="${TRAIN_MAX_PARALLEL:-1}" \
EVAL_MAX_PARALLEL="${EVAL_MAX_PARALLEL:-1}" \
MODEL_VARIANT="${MODEL_VARIANT:-auto}" \
SELECTION_PROTOCOL="${SELECTION_PROTOCOL:-shared_matched_validation}" \
SELECTION_VALIDATION_SEEDS="${SELECTION_VALIDATION_SEEDS:-114817}" \
SELECTION_VALIDATION_EPISODES="${SELECTION_VALIDATION_EPISODES:-10}" \
SELECTION_VALIDATION_CANDIDATES="${SELECTION_VALIDATION_CANDIDATES:-$CHECKPOINT_CANDIDATES}" \
POST_EVAL_VALIDATION_SEED="${POST_EVAL_VALIDATION_SEED:-114817}" \
POST_EVAL_VALIDATION_CANDIDATES="${POST_EVAL_VALIDATION_CANDIDATES:-$CHECKPOINT_CANDIDATES}" \
EVAL_FR_MODE="${EVAL_FR_MODE:-checkpoint}" \
SUMMARY_FILENAME_TAG="${SUMMARY_FILENAME_TAG:-model_fr}" \
STRICT_SUMMARY="${STRICT_SUMMARY:-1}" \
AGENT_SIZE="${AGENT_SIZE:-0.5}" \
GROUP_B_PEAK_JITTER_RANGE="${GROUP_B_PEAK_JITTER_RANGE:-15.0}" \
GROUP_B_PEAK_CENTER_JITTER_RANGE="${GROUP_B_PEAK_CENTER_JITTER_RANGE:-3.0}" \
GROUP_B_PEAK_HEIGHT_JITTER_RATIO_MIN="${GROUP_B_PEAK_HEIGHT_JITTER_RATIO_MIN:-0.20}" \
GROUP_B_PEAK_HEIGHT_JITTER_RATIO_MAX="${GROUP_B_PEAK_HEIGHT_JITTER_RATIO_MAX:-0.40}" \
GROUP_B_PEAK_HEIGHT_MAX_SCALE="${GROUP_B_PEAK_HEIGHT_MAX_SCALE:-1.30}" \
GROUP_B_TERRAIN_VARIANT_NOISE_RATIO="${GROUP_B_TERRAIN_VARIANT_NOISE_RATIO:-0.15}" \
GROUP_B_SEMI_RANDOM_HOLD_MODE="${GROUP_B_SEMI_RANDOM_HOLD_MODE:-fixed}" \
GROUP_B_SEMI_RANDOM_HOLD_EPISODES="${GROUP_B_SEMI_RANDOM_HOLD_EPISODES:-5}" \
GROUP_B_SEMI_RANDOM_HOLD_MIN_EPISODES="${GROUP_B_SEMI_RANDOM_HOLD_MIN_EPISODES:-5}" \
GROUP_B_SEMI_RANDOM_HOLD_MAX_EPISODES="${GROUP_B_SEMI_RANDOM_HOLD_MAX_EPISODES:-5}" \
CROSS_AGENT_REFERENCE_START_EPISODE="$CROSS_REF_START_EPISODE" \
CROSS_AGENT_REFERENCE_ACTOR_START_EPISODE="$CROSS_REF_ACTOR_START_EPISODE" \
CROSS_AGENT_REFERENCE_ACTOR_RAMP_EPISODES="$CROSS_REF_ACTOR_RAMP_EPISODES" \
CROSS_AGENT_REFERENCE_ACTOR_REQUIRE_SUCCESS="$CROSS_REF_ACTOR_REQUIRE_SUCCESS" \
XLA_GLOBAL="${XLA_GLOBAL:-1}" \
JIT_COMPILE="${JIT_COMPILE:-1}" \
FORCE_OUTER_JIT_COMPILE="${FORCE_OUTER_JIT_COMPILE:-0}" \
CUDA_LAUNCH_BLOCKING="${CUDA_LAUNCH_BLOCKING:-0}" \
TF_SYNC_ON_FINISH="${TF_SYNC_ON_FINISH:-0}" \
XLA_COMPILE_PARALLELISM="${XLA_COMPILE_PARALLELISM:-1}" \
WORKER_LAUNCH_STAGGER_SECONDS="${WORKER_LAUNCH_STAGGER_SECONDS:-90}" \
REUSE="${REUSE:-0}" \
TRAIN_REUSE="${TRAIN_REUSE:-0}" \
FORCE_RERUN="${FORCE_RERUN:-1}" \
FORCE_POST_EVAL_RERUN="${FORCE_POST_EVAL_RERUN:-1}" \
FORCE_POST_EVAL_TESTSET_REGEN="${FORCE_POST_EVAL_TESTSET_REGEN:-0}" \
PYTHON_BIN="${PYTHON_BIN:-/home/tang/miniconda3/envs/maddpg_env/bin/python3}" \
bash "$ROOT_DIR/run_level3_dual_semantics_train_eval_official.sh"
