#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="/home/tang/matd3"
cd "$ROOT_DIR"

LABELS="matd3_full_dual_semantic matd3_cross_agent_ref_agent_success matd3_cross_agent_ref_agent_quality matd3_cross_agent_ref_soft_advantage matd3_cross_agent_ref_selector_mix matd3_cross_agent_ref_reward_to_success_selector matd3_cross_agent_ref_progress_gate matd3_cross_agent_ref_no_quality_gate matd3_cross_agent_ref_behavior_label matd3_cross_agent_ref_agent_success_behavior_label"

RUN_TAG="${RUN_TAG:-level3_xref_strong_hold5_seed101_ep1200_matchedval_official10x30_$(date +%Y%m%d_%H%M%S)}"

TRAIN_LABELS_OVERRIDE="${TRAIN_LABELS_OVERRIDE:-$LABELS}" \
EVAL_LABELS_OVERRIDE="${EVAL_LABELS_OVERRIDE:-$LABELS}" \
RUN_TAG="$RUN_TAG" \
TRAIN_SEEDS="${TRAIN_SEEDS:-101}" \
EVAL_SEEDS="${EVAL_SEEDS:-30088 30188 30288 30388 30488 30588 30688 30788 30888 30988}" \
EPISODES="${EPISODES:-1200}" \
TRAIN_EPISODES="${TRAIN_EPISODES:-1200}" \
EVAL_EPISODES="${EVAL_EPISODES:-30}" \
POST_EVAL_EPISODES="${POST_EVAL_EPISODES:-30}" \
MAX_PARALLEL="${MAX_PARALLEL:-3}" \
MODEL_VARIANT="${MODEL_VARIANT:-auto}" \
SELECTION_PROTOCOL="${SELECTION_PROTOCOL:-shared_matched_validation}" \
SELECTION_VALIDATION_SEEDS="${SELECTION_VALIDATION_SEEDS:-114817}" \
SELECTION_VALIDATION_EPISODES="${SELECTION_VALIDATION_EPISODES:-10}" \
SELECTION_VALIDATION_CANDIDATES="${SELECTION_VALIDATION_CANDIDATES:-best_by_team_sr,best,checkpoint,final,latest_ep}" \
POST_EVAL_VALIDATION_SEED="${POST_EVAL_VALIDATION_SEED:-114817}" \
EVAL_FR_MODE="${EVAL_FR_MODE:-checkpoint}" \
SUMMARY_FILENAME_TAG="${SUMMARY_FILENAME_TAG:-model_fr}" \
STRICT_SUMMARY="${STRICT_SUMMARY:-1}" \
AGENT_SIZE="${AGENT_SIZE:-0.5}" \
GROUP_B_PEAK_JITTER_RANGE="${GROUP_B_PEAK_JITTER_RANGE:-15.0}" \
GROUP_B_PEAK_CENTER_JITTER_RANGE="${GROUP_B_PEAK_CENTER_JITTER_RANGE:-3.0}" \
GROUP_B_PEAK_HEIGHT_JITTER_RATIO_MIN="${GROUP_B_PEAK_HEIGHT_JITTER_RATIO_MIN:-0.20}" \
GROUP_B_PEAK_HEIGHT_JITTER_RATIO_MAX="${GROUP_B_PEAK_HEIGHT_JITTER_RATIO_MAX:-0.40}" \
GROUP_B_PEAK_HEIGHT_MAX_SCALE="${GROUP_B_PEAK_HEIGHT_MAX_SCALE:-1.30}" \
GROUP_B_TERRAIN_VARIANT_NOISE_RATIO="${GROUP_B_TERRAIN_VARIANT_NOISE_RATIO:-0.15}" \
GROUP_B_SEMI_RANDOM_HOLD_MODE="${GROUP_B_SEMI_RANDOM_HOLD_MODE:-fixed}" \
GROUP_B_SEMI_RANDOM_HOLD_EPISODES="${GROUP_B_SEMI_RANDOM_HOLD_EPISODES:-5}" \
GROUP_B_SEMI_RANDOM_HOLD_MIN_EPISODES="${GROUP_B_SEMI_RANDOM_HOLD_MIN_EPISODES:-5}" \
GROUP_B_SEMI_RANDOM_HOLD_MAX_EPISODES="${GROUP_B_SEMI_RANDOM_HOLD_MAX_EPISODES:-5}" \
XLA_GLOBAL="${XLA_GLOBAL:-1}" \
JIT_COMPILE="${JIT_COMPILE:-1}" \
FORCE_OUTER_JIT_COMPILE="${FORCE_OUTER_JIT_COMPILE:-0}" \
CUDA_LAUNCH_BLOCKING="${CUDA_LAUNCH_BLOCKING:-0}" \
TF_SYNC_ON_FINISH="${TF_SYNC_ON_FINISH:-0}" \
XLA_COMPILE_PARALLELISM="${XLA_COMPILE_PARALLELISM:-1}" \
WORKER_LAUNCH_STAGGER_SECONDS="${WORKER_LAUNCH_STAGGER_SECONDS:-90}" \
REUSE="${REUSE:-0}" \
TRAIN_REUSE="${TRAIN_REUSE:-0}" \
FORCE_RERUN="${FORCE_RERUN:-0}" \
FORCE_POST_EVAL_RERUN="${FORCE_POST_EVAL_RERUN:-0}" \
FORCE_POST_EVAL_TESTSET_REGEN="${FORCE_POST_EVAL_TESTSET_REGEN:-0}" \
PYTHON_BIN="${PYTHON_BIN:-/home/tang/miniconda3/envs/maddpg_env/bin/python3}" \
bash "$ROOT_DIR/run_level3_dual_semantics_train_eval_official.sh"
